[package]
name = "wo"
version = "0.2.0"
edition = "2021"
description = "Zeigt an, wo sich Personen laut Home Assistant befinden"

[[bin]]
name = "wo"
path = "src/main.rs"

[dependencies]
ureq = { version = "2", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
windows-sys = { version = "0.59", features = ["Win32_Foundation", "Win32_Security_Cryptography", "Win32_System_Console"] }

[profile.release]
opt-level = "s"
lto = true
strip = true
panic = "abort"
